/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Category: typeof import('./src/components/category.vue')['default']
    ChatAnswer: typeof import('./src/components/chat/ChatAnswer.vue')['default']
    ChatEvent: typeof import('./src/components/chat/ChatEvent.vue')['default']
    ChatMessage: typeof import('./src/components/chat/ChatMessage.vue')['default']
    ChatReason: typeof import('./src/components/chat/ChatReason.vue')['default']
    ChatRelated: typeof import('./src/components/chat/ChatRelated.vue')['default']
    ChatSenderBox: typeof import('./src/components/chat/ChatSenderBox.vue')['default']
    ChatSource: typeof import('./src/components/chat/ChatSource.vue')['default']
    Engine: typeof import('./src/components/engine.vue')['default']
    Footer: typeof import('./src/components/footer.vue')['default']
    Header: typeof import('./src/components/header.vue')['default']
    History: typeof import('./src/components/history.vue')['default']
    Language: typeof import('./src/components/language.vue')['default']
    Media: typeof import('./src/components/media.vue')['default']
    Models: typeof import('./src/components/models.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./src/components/settings.vue')['default']
    TAlert: typeof import('tdesign-vue-next')['Alert']
    TBadge: typeof import('tdesign-vue-next')['Badge']
    TButton: typeof import('tdesign-vue-next')['Button']
    TChat: typeof import('@tdesign-vue-next/chat')['Chat']
    TChatContent: typeof import('@tdesign-vue-next/chat')['ChatContent']
    TChatItem: typeof import('@tdesign-vue-next/chat')['ChatItem']
    TChatLoading: typeof import('@tdesign-vue-next/chat')['ChatLoading']
    TChatReasoning: typeof import('@tdesign-vue-next/chat')['ChatReasoning']
    TChatSender: typeof import('@tdesign-vue-next/chat')['ChatSender']
    TDialog: typeof import('tdesign-vue-next')['Dialog']
    TDivider: typeof import('tdesign-vue-next')['Divider']
    TDropdown: typeof import('tdesign-vue-next')['Dropdown']
    TForm: typeof import('tdesign-vue-next')['Form']
    TFormItem: typeof import('tdesign-vue-next')['FormItem']
    TImage: typeof import('tdesign-vue-next')['Image']
    TImageViewer: typeof import('tdesign-vue-next')['ImageViewer']
    TLink: typeof import('tdesign-vue-next')['Link']
    TLoading: typeof import('tdesign-vue-next')['Loading']
    TMenu: typeof import('tdesign-vue-next')['Menu']
    TMenuItem: typeof import('tdesign-vue-next')['MenuItem']
    ToolCallBox: typeof import('./src/components/chat/ToolCallBox.vue')['default']
    TOption: typeof import('tdesign-vue-next')['Option']
    TPopup: typeof import('tdesign-vue-next')['Popup']
    TSelect: typeof import('tdesign-vue-next')['Select']
    TSkeleton: typeof import('tdesign-vue-next')['Skeleton']
    TSlider: typeof import('tdesign-vue-next')['Slider']
    TSwitch: typeof import('tdesign-vue-next')['Switch']
    TTag: typeof import('tdesign-vue-next')['Tag']
    TTextarea: typeof import('tdesign-vue-next')['Textarea']
    TTooltip: typeof import('tdesign-vue-next')['Tooltip']
  }
}
