export default {
  title: 'Search with AI',
  theme: 'Theme',
  answer: 'Answer',
  related: 'Related',
  sources: 'Sources',
  copy: 'Copy',
  reload: 'Reload',
  search: 'Engine',
  sogou: 'Sogou',
  bing: 'Bing',
  google: 'Google',
  searxng: 'SearXNG',
  llm: 'LLM',
  language: 'Language',
  settings: 'Settings',
  selectModel: 'Select LLM',
  selectEngine: 'Select Search Engine',
  localModel: 'Local LLM',
  enableLocalModel: 'Enable Local LLM',
  warning: 'Content is generated by AI and accuracy cannot be guaranteed',
  message: {
    queryError: 'Query error',
    copyError: 'Copy failed',
    noSelect: 'Not selected yet',
    sourceError: 'Failed to obtain information'
  },
  tips: {
    search: 'Ask a question.'
  }
};
