export default {
  title: 'AI Search',
  theme: 'Theme',
  ask: 'Ask Me',
  answer: 'Answer',
  reasoning: 'Think It Through',
  related: 'You Might Also Ask',
  sources: 'Sources',
  media: 'Media',
  copy: 'Copy',
  reload: 'Try Again',
  share: 'Share',
  search: 'Search Engine',
  deepResearch: 'Dig Deeper',
  researchGoal: 'What Are You Trying to Find?',
  webSearch: 'Search the Web',
  newChat: 'Start Over',
  sogou: 'Sogou',
  chatglm: 'ChatGLM',
  bing: 'Bing',
  google: 'Google',
  searxng: 'SearXNG',
  llm: 'AI Model',
  chat: 'Ask More',
  back: 'Back Home',
  language: 'Language',
  settings: 'Settings',
  selectModel: 'Pick a Model',
  selectLanguage: 'Pick a Language',
  selectEngine: 'Pick a Search Engine',
  localModel: 'Local AI',
  localProvider: 'Local Provider',
  selectProvider: 'Pick a Provider',
  provider: 'Provider',
  enableLocalModel: 'Use Local Model',
  warning: 'Heads up: This content was generated by AI and might not be 100% accurate.',
  progress: {
    start: 'Starting...',
    analyzing: 'Looking into it...',
    searching: 'Searching...',
    researching: 'Researching...',
    reading: 'Reading stuff...',
    summarizing: 'Breaking it down...',
    reporting: 'Wrapping it up...',
    done: 'All set!',
    failed: 'Something went wrong.'
  },
  message: {
    queryError: 'Oops! Something went wrong with your question.',
    copyError: 'Couldn’t copy that.',
    noSelect: 'Nothing selected yet.',
    sourceError: 'Couldn’t get the info.',
    shareSuccess: 'Link copied! Ready to share.',
    noRelated: 'No similar questions found.',
    success: 'Done!'
  },
  category: {
    general: 'Everything',
    science: 'Science',
    images: 'Images',
    videos: 'Videos'
  },
  mode: {
    simple: 'Quick Mode',
    deep: 'Detailed Mode',
    research: 'Research Mode'
  },
  tips: {
    search: 'Ask anything you’re curious about.',
    continue: 'Keep going — ask something based on this.'
  },
  btn: {
    clear: 'Clear History'
  },
  step: 'Step', // For the step number in the reasoning
  reasoningProcess: 'Reasoning Process', // Title for the reasoning section
  loadMore: 'Load More' // If you implemented a "load more" for reasoning steps
};
